apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: go-cache-local-path
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: npm-cache-local-path
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: docker-cache-local-path
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: todanni-github-runner
spec:
  replicas: 2
  organization: todanni
  image: stegzilla/todanni-actions-runner
  selector:
    matchLabels:
      app: todanni-github-runner
  serviceName: todanni-github-runner
  template:
    metadata:
      labels:
        app: todanni-github-runner
    spec:
      containers:
        - name: runner
          env:
            - name: GOMODCACHE
              value: "/home/runner/.cache/go-mod"
          volumeMounts:
            - name: go-cache
              mountPath: "/home/runner/.cache"
            - name: npm-cache
              mountPath: "/home/runner/.npm"
        - name: docker
          volumeMounts:
            - name: docker-cache
              mountPath: /var/lib/docker
  volumeClaimTemplates:
    - metadata:
        name: go-cache
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
        storageClassName: go-cache-local-path
    - metadata:
        name: npm-cache
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
        storageClassName: npm-cache-local-path
    - metadata:
        name: docker-cache
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
        storageClassName: docker-cache-local-path
